apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-apps
spec:
  generators:
  - git:
      repoURL: https://github.com/alexmt/argo-ecosystem-demo.git
      revision: HEAD
      directories:
      - path: '*'
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/alexmt/argo-ecosystem-demo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
