apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

openapi:
 path: rollout_cr_schema.json

patchesStrategicMerge:
- canary-demo-rollout-patch.yaml

resources:
- https://github.com/argoproj/rollouts-demo//examples/canary
