apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- argo-rollouts-notification-configmap-patch.yaml

resources:
- https://github.com/argoproj/argo-rollouts/releases/download/v1.1.0-rc2/install.yaml
- https://github.com/argoproj/argo-rollouts/releases/download/v1.1.0-rc2/notifications-install.yaml
