apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- https://github.com/argoproj/argo-rollouts/releases/download/v1.0.7/install.yaml
- https://raw.githubusercontent.com/argoproj/argo-rollouts/master/manifests/notifications-install.yaml
