apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-apps
spec:
  generators:
  - git:
      repoURL: https://github.com/alexmt/argo-ecosystem-demo.git
      revision: HEAD
      directories:
      - path: '*'
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        argocd-image-updater.argoproj.io/demo.update-strategy: name
        argocd-image-updater.argoproj.io/git-branch: auto-upgrade
        argocd-image-updater.argoproj.io/image-list: demo=argoproj/rollouts-demo
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/github-creds
        notifications.argoproj.io/subscribe.app-sync-running.slack: argoproj-deployments-notifications
    spec:
      project: default
      source:
        repoURL: https://github.com/alexmt/argo-ecosystem-demo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
