apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- https://raw.githubusercontent.com/argoproj-labs/applicationset/master/manifests/install.yaml
- https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.10.3/manifests/install.yaml
- rollouts-extension.yaml
- appset.yaml

components:
- https://github.com/argoproj-labs/argocd-extensions/manifests

images:
- name: quay.io/argoproj/argocd
  newName: ghcr.io/argoproj/argocd
  newTag: 2.2.0-d8d7b30f
